# Setup
title:               Namit Saxena
tagline:             'Blog and Notes'
description:         '<a href="http://www.namitsaxena.com" target="_blank">Namit Saxena:</a> Personal Notes and Thoughts'
url:                 https://namitsaxena.github.io
baseurl:             ""
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Namit Saxena
  url:               http://www.namitsaxena.com
  email:             info@namitsaxena.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-123456-78
